version: "3.9"

  
services: 
  frontend_app_main:

    build: frontend/frontend_app_main/
    restart: unless-stopped
    ports:
        - ':3006:3006'
    command: >
              sh -c " 
                      echo    && 
                      echo  running frontend_app_main ....  &&
                      echo   &&
                      ./start-reload.sh
                    "
    networks:
          - myAppNetwork
  angular_frontend_app:

    build: frontend/angular_frontend_app/
    restart: unless-stopped
    ports:
        - '3007:4200'
    command: >
              sh -c " 
                      echo    && 
                      echo  running angular_frontend_app ....  &&
                      echo   &&
                      ./start-reload.sh
                    "
    networks:
          - myAppNetwork

  auth_app:   

      build:
        context: backend/auth_app/
        dockerfile: Dockerfile
      ports:
          - '3101:3101'
      networks:
          - myAppNetwork
      depends_on:
          - pgsql
      command: >
                sh -c "
                        echo    && 
                        echo running auth_app ....  &&
                        echo    && 
                        ./start-reload.sh
                      "

  pgsql:
  
    image: 'postgres:15'
    
    ports: 
        - '5432:5432'
    
    environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        
    volumes:
        - 'my_db_vol:/var/lib/postgresql/data'
    networks:
        - myAppNetwork

   
networks:
    myAppNetwork:
        driver: bridge

volumes:
    my_db_vol:
        driver: local